## Makefile for building the gpsim with gcc for mingw. The build
## uses tools running on cygwin, however.

## Use: make -f makefile.mingw

PARTS=gpsim modules
CLEAN_PARTS=$(PARTS) cli src gui

all :
	for D in $(PARTS); do (cd $$D && $(MAKE) -f makefile.mingw all); done

clean :
	for D in $(CLEAN_PARTS); do (cd $$D && $(MAKE) -f makefile.mingw clean); done
